### ISSUE TITLE
Notify users of new updates

### ISSUE THREAD

**Issue by airmencoders** [airmencoders/MQF#17]
Add a mechanism to notify users when there is a new update and give them directions on how to update with BB Work. (https://airmencoders.us/MQF#how-do-i-update-the-app)

Since we don't currently have server, thinking about setting that to trigger every 3 weeks. Thoughts?

**Comment by cbrech** [comment]
Added in v1.6.7
Notifies user every 30 days

**Comment by cralor** [comment]
Good idea -- too bad BB apps isn't a good service.
