### ISSUE TITLE
Add C-130J Image

### ISSUE THREAD

**Issue by cbrech** [airmencoders/MQF#22]

**Comment by cralor** [comment]
It looks like you have one committed, but here's a couple more I have found on DVIDS:

https://www.dvidshub.net/image/6167069/yokota-c-130j-tactics-rodeo-2020
https://www.dvidshub.net/image/6167074/yokota-c-130j-tactics-rodeo-2020

**Comment by cbrech** [comment]
ooh I like it. Just committed a new one to Pre-Release
