### ISSUE TITLE
Add KC-135 MQFs

### ISSUE THREAD

**Issue by airmencoders** [airmencoders/MQF#5]

**Comment by taylorjason** [comment]
Was thinking about this...has there been consideration for putting the MQF into a table (excel, airtable, etc) format that the community, or perhaps even OGV/A3V could maintain?  If there is a standardized table format and naming convention, converting to JSON to be added to the application would not be too difficult.  This would also allow for the MQF JSON to live on a server and be downloaded to the app whenever it updates versus being hard coded into the app.

Perhaps this is all already discussed and part of the roadmap. Glad to help where I can, not much of a coder but I know some basics and am willing to learn more. Let me know if I'm off base here or where I can help.

**Comment by airmencoders** [comment]
@taylorjason We have been wrestling with how to best accomplish this. Thinking about a static website that lets users create and edit MQFs: https://github.com/airmencoders/MQF/issues/7#issuecomment-581099966

**Comment by taylorjason** [comment]
Makes good sense. My thought process was something to enforce a structure and format eSy to ingest while removing the burden from the app developers.
